# logBack配置
logging:
  path: logs
  level:
    com.answern.testplat: debug 
  file: ${logging.path}/testplat.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}: %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"