### Mybatis 配置
mybatis:
  mapperLocations:   classpath:/com/answern/testplat/**/mapper/**Mapper.xml
  typeAliasesPackage: com.answern.testplat.**.bins   #entity扫描的包名
   
spring: 
  mvc: 
    view: 
      prefix: /templates/
      suffix: .ftl
##pagehelper分页插件配置
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params-count: countSql
