spring: 
  redis:
    host: localhost  
    port: 6379    
    timeout: 60000
    database: 0 
    pool: 
      max-active: -1     # 连接池最大连接数（使用负值表示没有限制）
      max-wait:   -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle:   8      # 连接池中的最大空闲连接
      min-idle:   0      # 连接池中的最小空闲连接
      max-total:  200
      holed: 2000